font_family JetBrainsMono Nerd Font
font_size 12.5

# background_image /home/hoangdesamac/Pictures/wallpapers/Anime-Purple-eyes.png
# background_image_layout scaled
# background_image_opacity 0.3
background_opacity 0.55
