# =============================================
# 1. CẤU HÌNH CHUNG
# =============================================
set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g mouse on

unbind %
bind '\' split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

unbind r 
# tmux source-file ~/.tmux.conf \;
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# Copy vim movements
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# new window
bind c new-window -c '#{pane_current_path}'

# start from 1, not 0
set-option -g base-index 1
# re-number when closing windows
set-option -g renumber-windows on

# =============================================
# 2. QUẢN LÝ PLUGIN
# =============================================
set -g @plugin 'tmux-plugins/tpm'

# =============================================
# 3. TMUX2K STATUS BAR (CẤU HÌNH GIAO DIỆN)
# =============================================
set -g @plugin '2kabhishek/tmux2k'

# --- Giao diện & Theme ---
set -g @tmux2k-theme 'catppuccin'  
set -g @tmux2k-icons-only false

# TMUX2K TRANSPARENT
set -g @tmux2k-theme 'transparent'
# --- Sắp xếp module (Layout) theo yêu cầu ---

# BÊN TRÁI: Session (Số) -> Git -> Cwd (Đường dẫn)
set -g @tmux2k-left-plugins "session git cwd"

# BÊN PHẢI: Cpu -> Ram -> Battery (Pin) -> Time (Giờ)
# (Đã bỏ Network vì bạn không yêu cầu trong danh sách mới)
set -g @tmux2k-right-plugins "cpu ram battery time"

# --- Tinh chỉnh hiển thị ---

# 1. Cấu hình Đường dẫn (CWD)
# Giới hạn độ dài đường dẫn để không bị chiếm hết màn hình (ví dụ 25 ký tự)
set -g @tmux2k-cwd-length 25

# 2. Cấu hình Giờ
set -g @tmux2k-time-format "%H:%M"

# 3. Căn giữa danh sách cửa sổ
set -g @tmux2k-window-list-alignment 'centre'

# --- Fix Icon lỗi ---
set -g @tmux2k-ram-icon ""

# =============================================
# 4. LƯU PHIÊN LÀM VIỆC
# =============================================
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'


# =============================================
# 5. KHỞI CHẠY (LUÔN Ở CUỐI)
# =============================================
run '~/.tmux/plugins/tpm/tpm'

